ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get install libusb-1.0-0-dev
RUN git clone https://github.com/nityc-d-robo/usb_connect.git && cd usb_connect && mkdir build && cd build && cmake .. && make install
RUN git clone https://github.com/nityc-d-robo/motor_lib.git && cd motor_lib && mkdir build && cd build && cmake .. && make install

